#! /bin/bash
# /etc/init.d/boot_twin

### BEGIN INIT INFO
# Provides: boot_twin
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Run twin at boot.
# Description: Run twin at boot.
### END INIT INFO

case "$1" in
  start)
    cd /home/pi/Desktop/Evil_Twin/
    ./twin.sh
    ;;
  stop)
    # ?
    ;;
  *)
    echo "Usage: /etc/init.d/boot_twin {start|stop}"
    exit 1
    ;;
esac

exit 0
